// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spruce_Wood_Loggers_ERP;

#nullable disable

namespace Spruce_Wood_Loggers_ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809020523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Batch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("length")
                        .HasColumnType("double precision");

                    b.Property<int>("numPieces")
                        .HasColumnType("integer");

                    b.Property<double>("thickness")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("timeProcessed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("width")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Database_Objects.CutLength", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("length")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("length")
                        .IsUnique();

                    b.ToTable("CutLengths");
                });

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Database_Objects.CutSize", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("thickness")
                        .HasColumnType("double precision");

                    b.Property<double>("width")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("thickness", "width")
                        .IsUnique();

                    b.ToTable("CutSizes");
                });

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Database_Objects.StandardNumPieces", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("numPieces")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("numPieces")
                        .IsUnique();

                    b.ToTable("StandardNumPieces");
                });

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Database_Objects.StandardSizeRelationship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("CutSizeId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardNumPiecesId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CutSizeId");

                    b.HasIndex("StandardNumPiecesId", "CutSizeId")
                        .IsUnique();

                    b.ToTable("StandardSizeRelationships");
                });

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Database_Objects.StandardSizeRelationship", b =>
                {
                    b.HasOne("Spruce_Wood_Loggers_ERP.Database_Objects.CutSize", "CutSize")
                        .WithMany()
                        .HasForeignKey("CutSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spruce_Wood_Loggers_ERP.Database_Objects.StandardNumPieces", "StandardNumPieces")
                        .WithMany()
                        .HasForeignKey("StandardNumPiecesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CutSize");

                    b.Navigation("StandardNumPieces");
                });
#pragma warning restore 612, 618
        }
    }
}
