// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spruce_Wood_Loggers_ERP;

#nullable disable

namespace Spruce_Wood_Loggers_ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spruce_Wood_Loggers_ERP.Batch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("length")
                        .HasColumnType("double precision");

                    b.Property<int>("numPieces")
                        .HasColumnType("integer");

                    b.Property<double>("thickness")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("timeProcessed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("width")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
